apiVersion: apps/v1
kind: Deployment
metadata:
  name: perftest-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: perftest
  template:
    metadata:
      labels:
        app: perftest
    spec:
      containers:
      - name: perftest
        image: gueraf/perftest
        command: ["/bin/sh", "-c", "sleep infinity"]
